def print_exception_integer() -> print:
    print(50*'!')
    print('ALERTA: Digite um número inteiro válido.')
    print(50*'!')